services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./logs:/logs
    command: >
      postgres -c logging_collector=on
               -c log_destination=stderr
               -c log_directory='/logs'
               -c log_filename='db.log'
               -c log_statement=all
    restart: always

  web:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
      POSTGRES_HOST: db
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --log-config /app/app/logging.ini"
    restart: always

volumes:
  db_data:
